### ISSUE TITLE
Crash on switching off the internet

### ISSUE THREAD

**Issue by rranjan14** [ezranbayantemur/react-native-rtmp-publisher#9] opened 2022-12-21 10:55 UTC
**Describe the bug**
As soon as the internet connection is closed, `handleOnConnectionFailed` handler is called and the app crashes.

**To Reproduce**
1. Create a View with <RTMPPublisher />
2. Start streaming.
3. Switch off the internet.
4. Application crashes as soon as the `handleOnConnectionFailed` callback is received

**Expected behavior**
Streaming should stop but the application should not crash.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 13
 - React Native v0.70.6
 - Package version 0.4.4

**Stacktrace:**
[Link to stacktrace](https://drive.google.com/file/d/1pAGBzshTcNfiFtJ9T2xABddzlRcuKDjD/view?usp=share_link)

**Comment by ezranbayantemur** [comment] 2023-01-01 22:58
Hello, @rranjan14 
I tried to reproduce that issue but my app didn't crashed. I updated android package to 2.2.2 by 0.4.5 version.

Can you try it again?

**Comment by rranjan14** [comment] 2023-01-02 07:22
I did try. Same result again. I get `Error send packet, Broken pipe` message  in the `onConnectionFailed` handler, and then it crashes.

**Comment by ezranbayantemur** [comment] 2023-01-07 22:53
I've tried to reproduce your issue but it looks like its not crashing. Maybe it's about your device. I think looking at logcat outputs will help 

https://user-images.githubusercontent.com/42299721/211173192-1ba65ad0-6ca1-449e-bebb-95a95ec8b508.mov

**Comment by rranjan14** [comment] 2023-01-08 08:50
I'll verify once again and attach the log file if i encounter the same issue.

**Comment by rranjan14** [comment] 2023-01-09 16:46
https://user-images.githubusercontent.com/47914095/211361641-52f9bd6d-1c65-42bf-8d1f-1834ef138d08.mp4

Not sure of the behaviour on emulator, but on real device, it still is crashing.

**Comment by ezranbayantemur** [comment] 2023-01-20 21:04
Yes, can you give me the Logcat output of the crash timestamps?

**Comment by ezranbayantemur** [comment] 2023-01-29 11:59
@rranjan14 I'm closing this issue as resolved. You can open it again if it happens again.

**Closed** 2023-01-29 11:59 UTC
